src/main/java/com/plana/infli/InfliApplication.java, src/main/java/com/plana/infli/config/QueryDslConfig.java, src/main/java/com/plana/infli/domain/BaseEntity.java, src/main/java/com/plana/infli/domain/Board.java, src/main/java/com/plana/infli/domain/University.java, src/main/java/com/plana/infli/repository/board/BoardRepository.java, src/main/java/com/plana/infli/repository/board/BoardRepositoryCustom.java, src/main/java/com/plana/infli/repository/board/BoardRepositoryImpl.java, src/main/java/com/plana/infli/repository/university/UniversityRepository.java, src/main/java/com/plana/infli/repository/university/UniversityRepositoryCustom.java, src/main/java/com/plana/infli/repository/university/UniversityRepositoryImpl.java, src/main/java/com/plana/infli/service/BoardService.java, src/main/java/com/plana/infli/service/UniversityService.java, src/main/java/com/plana/infli/web/controller/BoardController.java, src/main/java/com/plana/infli/web/controller/UniversityController.java, src/main/java/com/plana/infli/web/dto/request/board/BoardCreateRequest.java, src/main/java/com/plana/infli/web/dto/request/university/UniversityCreateRequest.java
- Domain, Web, Service, Repository 디렉토리 및 필요 클래스 생성
- BaseEntity 생성, JpaAuditing 활성
- Board, University 엔티티 생성 
프로젝트 프레임 생성 
테스트가 존재하지 않으므로, 디렉토리 화면 캡쳐합니다.
close #6
close #7
close #8
close #9
- 피드백 주시면 감사하겠습니다.
=> (#6) 스프링 부트 초기 설정 2

.gitignore, src/main/java/com/plana/infli/config/AWSConfig.java, src/main/java/com/plana/infli/domain/Image.java, src/main/java/com/plana/infli/repository/post/ImageRepository.java, src/main/java/com/plana/infli/service/ImageService.java, src/main/java/com/plana/infli/utils/S3Uploader.java, src/main/java/com/plana/infli/web/controller/ImageController.java, src/main/java/com/plana/infli/web/dto/request/image/ImageCreateRs.java
- 이미지 관련 기능 작업
- 이미지 MVC 추가
- AWS S3 설정
- S3 Uploader 유틸 추가
close #16 
close #17 
close #18 
close #19 
- aws.yml 이 따로 있어야 합니다. 추후 [infli-server-config](https://github.com/Plan-A-project/infli-server-config) 레포지토리에 추가 예정.
=> (#16) 이미지 관련 기능 작업

deploy/Dockerfile, deploy/Jenkinsfile, deploy/deploy.sh, deploy/nginx.conf, src/main/java/com/plana/infli/config/SecurityConfig.java, src/main/java/com/plana/infli/domain/Comment.java, src/main/java/com/plana/infli/repository/comment/CommentRepositoryImpl.java
- 개발 서버 배포용 스크립트를 작성
- jenkins를 통해 개발 서버에 배포합니다
- 테스트 결과 추후 첨부
- 
close #67 
=> 개발 서버 배포 스크립트 작성 (#67)

src/main/java/com/plana/infli/config/SecurityConfig.java, src/main/java/com/plana/infli/domain/Post.java, src/main/java/com/plana/infli/repository/post/PostRepository.java, src/main/java/com/plana/infli/web/controller/ImageController.java, src/main/java/com/plana/infli/web/controller/PostController.java
- 스웨거 이슈 처리 및 코드 수정
- Post, Image 컨트롤러 path, 파라미터 수정
- SecurityConfig 수정
=> fix: 스웨거 이슈 처리

src/main/java/com/plana/infli/domain/PostLike.java, src/main/java/com/plana/infli/service/PostService.java
- `PostService` 변경 사항 추가
- 멤버 정보용 파라미터 변경
- 멤버 정보 조회 코드 추가
- 생략
=> chore: 파라미터 수정

src/main/java/com/plana/infli/domain/Post.java, src/main/java/com/plana/infli/exception/custom/BadRequestException.java, src/main/java/com/plana/infli/repository/board/BoardRepositoryCustom.java, src/main/java/com/plana/infli/repository/board/BoardRepositoryImpl.java, src/main/java/com/plana/infli/repository/comment/CommentRepositoryCustom.java, src/main/java/com/plana/infli/repository/comment/CommentRepositoryImpl.java, src/main/java/com/plana/infli/repository/member/MemberRepository.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryCustom.java, src/main/java/com/plana/infli/repository/post/PostRepositoryCustom.java, src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/service/BoardService.java, src/main/java/com/plana/infli/service/CommentLikeService.java, src/main/java/com/plana/infli/service/CommentService.java, src/main/java/com/plana/infli/web/controller/BoardController.java, src/main/java/com/plana/infli/web/controller/CommentController.java, src/main/java/com/plana/infli/web/controller/CommentLikeController.java, src/main/java/com/plana/infli/web/dto/request/comment/view/post/controller/LoadCommentsInPostRequest.java, src/main/java/com/plana/infli/web/dto/request/comment/view/post/service/LoadCommentsInPostServiceRequest.java, src/test/java/com/plana/infli/controller/CommentControllerTest.java, src/test/java/com/plana/infli/service/CommentIdentifierConcurrentTest.java, src/test/java/com/plana/infli/service/CommentServiceTest.java
(#88 )  댓글 API 문서 작성
- 댓글 관련 API 문서화 진행
- 댓글 관련 Swagger 작성 완료 
close #88
=>  [chore]: 댓글 API 문서 작성 (#88)

src/main/java/com/plana/infli/config/SecurityConfig.java
=> CORS 허용 (#90)

src/main/java/com/plana/infli/repository/post/PostRepositoryCustom.java, src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/service/CommentService.java, src/main/java/com/plana/infli/web/controller/BoardController.java, src/main/java/com/plana/infli/web/dto/response/comment/view/post/PostComment.java, src/test/java/com/plana/infli/service/CommentIdentifierConcurrentTest.java, src/test/java/com/plana/infli/service/CommentServiceTest.java
- 테스트 꺠짐 현상 해결 
- 테스트 꺠짐 및 빌드 실패 현상 해결 
close #92
=>  bug : 테스트 꺠짐 현상 해결 (#92)

src/main/java/com/plana/infli/config/SecurityConfig.java
- CORS 이슈 해결 2
- 테스트 결과 생략
close #94 
=> (#94) CORS 허용2

src/main/java/com/plana/infli/config/SecurityConfig.java
=> (#101) CORS OPTIONS 메서드 허용

src/main/java/com/plana/infli/config/SecurityConfig.java
- CORS expose header 추가
- 
close #103
=> (#103) CORS expose header 추가

src/main/java/com/plana/infli/domain/Post.java, src/main/java/com/plana/infli/domain/PostLike.java, src/main/java/com/plana/infli/repository/post/PostRepository.java, src/main/java/com/plana/infli/repository/postlike/PostLikeRepository.java, src/main/java/com/plana/infli/service/PostLikeService.java, src/main/java/com/plana/infli/service/PostService.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/controller/PostLikeController.java, src/main/java/com/plana/infli/web/dto/response/post/PostFindResponse.java
- 게시판 글 목록 조회 , 개별 조회, 내가 쓴 글 조회 api 기본 작업
- 게시글 좋아요 api 추가
- `Post` 조회수, 좋아요 수 칼럼 추가
- 추후 테스트 추가
close #48 
close #49 
close #50 
close #51 
close #52 
- 페이징, 인기글 쿼리 추후 추가 예정
=> (#48) Post 관련 구현 2

src/main/java/com/plana/infli/domain/Image.java, src/main/java/com/plana/infli/service/ImageService.java, src/main/java/com/plana/infli/service/PostLikeService.java, src/main/java/com/plana/infli/service/PostService.java, src/main/java/com/plana/infli/web/controller/ImageController.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/controller/PostLikeController.java
- `ResponseEntity` 반환 값 명시
- 컨트롤러, 서비스 코드 반환 값 명시
=> chore: 반환 값 명시

src/test/java/com/plana/infli/controller/MemberProfileControllerTest.java, src/test/java/com/plana/infli/service/MemberProfileServiceTest.java
- MemberProfileService 프로필 사진 변경 MockTest 삭제
- 프로필 사진 변경 MockTest 테스트 삭제
=> (#34) Member 관련 API 구현 2

src/main/java/com/plana/infli/config/SecurityConfig.java, src/main/java/com/plana/infli/domain/EmailAuthentication.java, src/main/java/com/plana/infli/domain/Member.java, src/main/java/com/plana/infli/service/MailService.java, src/main/java/com/plana/infli/service/MemberService.java, src/main/java/com/plana/infli/web/controller/AuthController.java, src/main/java/com/plana/infli/web/controller/MemberController.java, src/main/java/com/plana/infli/web/dto/request/member/CompanyMemberCreateRequest.java
- 기업 회원 가입 및 인증 API 구현
- 테스트 결과 이미지 첨부
close #123
=> 기업 회원 가입 및 인증 API 구현

src/main/java/com/plana/infli/service/MemberService.java
- 기업 회원 가입 트랜잭션 처리
- 테스트 결과 이미지 첨부
=> 기업 회원 가입 트랜잭션 처리

src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/dto/request/post/create/CreatePostRequest.java, src/main/java/com/plana/infli/web/dto/request/post/edit/EditPostRequest.java, src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardRequest.java, src/main/java/com/plana/infli/web/dto/response/post/board/BoardPost.java, src/main/java/com/plana/infli/web/dto/response/post/board/BoardPostsResponse.java
(#128 ) 글 생성, 글 수정 API 버그 수정
- 글 생성, 수정 API 정상 호출시 400 에러가 반환되는 문제 해결 
close #128
=> bug :글 생성, 글 수정 API 버그 수정   (#128)

src/test/java/com/plana/infli/service/MemberProfileServiceTest.java
(#130) 제목  빌드 꺠짐 현성 해결 
- 빌드 꺠짐 현상 해결, 
- 글 수정, 생성 API 정상 호출시에도 400에러 반환되는 문제 해결 
- 
close #130
=> bug : 빌드 꺠짐 현상 해결   (#130)

src/test/java/com/plana/infli/service/MemberProfileServiceTest.java
(#132) 빌드 꺠짐 현상 해결 2 
-빌드 꺠짐 현상 해결 
- 게시판 글 목록 조회 API에서 모집 관련 응답 데이터가 Swagger 에서 보이지 않는 문제 해결 
close #132
=> bug : 빌드 꺠짐 현상 해결 2 

src/main/java/com/plana/infli/config/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/web/dto/request/post/create/CreatePostRequest.java
(#135) 로컬 환경 더미 데이터 추가 
- 대학, 게시판 더미 데이터 생성 
close #135
=> chore : 로컬 환경 더미 데이터 추가 

src/main/java/com/plana/infli/web/controller/ImageController.java
(#137) 사진 전송 엔드포인트 URI 변경
- S3 사진 업로드 엔드포인트 URL 변경 
close #137
=> chore : 사진 전송 엔드포인트 URI 변경 (#137)

src/main/java/com/plana/infli/config/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/web/dto/request/post/create/CreatePostRequest.java, src/main/java/com/plana/infli/web/dto/request/post/edit/EditPostRequest.java, src/main/java/com/plana/infli/web/dto/request/post/view/PostQueryRequest.java, src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardRequest.java, src/main/java/com/plana/infli/web/dto/request/post/view/search/SearchPostsByKeywordRequest.java, src/main/java/com/plana/infli/web/dto/response/post/DefaultPostsResponse.java, src/main/java/com/plana/infli/web/dto/response/post/board/BoardPostsResponse.java, src/main/java/com/plana/infli/web/dto/response/post/my/MyPostsResponse.java
(#139) 글 목록 조회시 500 에러 발생하는 오류 수정 
close #139
=> bug : 글 목록 조회시 500 에러 발생하는 오류 수정  (#139)

src/main/java/com/plana/infli/config/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/config/initializer/MemberInitializer.java, src/main/java/com/plana/infli/domain/Board.java, src/main/java/com/plana/infli/domain/BoardType.java, src/main/java/com/plana/infli/domain/Member.java, src/main/java/com/plana/infli/domain/PostType.java, src/main/java/com/plana/infli/domain/Role.java, src/main/java/com/plana/infli/service/BoardService.java, src/main/java/com/plana/infli/service/PostService.java, src/main/java/com/plana/infli/web/controller/BoardController.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/dto/request/post/create/CreatePostRequest.java, src/main/java/com/plana/infli/web/dto/request/post/edit/EditPostRequest.java, src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardRequest.java, src/main/java/com/plana/infli/web/dto/request/post/view/search/SearchPostsByKeywordRequest.java, src/test/java/com/plana/infli/controller/BoardControllerTest.java
(#141) 글 작성 권한 검증 API 코드 리펙토링
- 게시판 유형별, 글 유형별, 회원 유형별 글 작성 권한 검증하는 API 리펙토링 
- 테스트 환경에서의 더미 데이터 생성 
close #141
=> Epic : 글 작성 권한 검증 API 코드 리펙토링  (#141)

src/main/java/com/plana/infli/config/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardRequest.java
(#143) 게시판 글 목록 조회 요청시 요청 파라미터 매핑 되지 않는 문제 해결
- 게시판 글 목록 조회 요청시 400 에러 응답하는 문제 해결 
close #143
=> bug : 게시판 글 목록 조회 요청시 요청 파라미터 매핑 되지 않는 문제 해결  (#143)

src/main/java/com/plana/infli/web/controller/CommentController.java
(#151 )빌드 꺠짐 현상 해결 
-  배포중 빌드가 꺠지는 문제 해결 
- ![image](https://github.com/Plan-A-project/infli-server/assets/99637164/03b02c67-035c-4e10-8838-32f05e49e73a)
close #151
=> bug  : 빌드 꺠짐 현상 해결  (#151)

src/main/java/com/plana/infli/service/PostService.java
(#153 ) 글 단건 조회시 500 에러 발생하는 문제 해결 
close #153
=> bug  : 글 단건 조회시 500 에러 발생하는 문제 해결   (#153)

src/main/java/com/plana/infli/repository/comment/CommentRepositoryImpl.java
(#155 ) 댓글 목록 조회시 500 에러 발생하는 문제 해결 
close #155
=>  bug : 댓글 목록 조회시 500 에러 발생하는 문제 해결  (#155)

src/main/java/com/plana/infli/web/controller/SettingController.java
(#175) 컴파일 오류 해결
- ServiceController 컴파일 오류 해결 
close #175
=> bug : 컴파일 오류 해결  (#175)

src/main/java/com/plana/infli/config/initializer/PostInitializer.java
=> bug : 빌드 꺠짐 현상 해결  (#185)

deploy/deploy.sh, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardRequest.java, src/main/java/com/plana/infli/web/dto/request/post/view/search/SearchPostsByKeywordRequest.java, src/test/java/com/plana/infli/controller/PostControllerTest.java
- 특정 게시판에 작성된 글 목록 조회시 400 에러 발생하는 버그 수정
close #187
=> bug : 특정 게시판에 작성된 글 목록 조회 API 버그 수정 (#187)

Dockerfile, buildspec.yml
[제목]  // 삭제하고 작성
(#209) Aws Codebuild 환경 구축
- Dockerfile, buildspec.yml 파일 수정
close #209
=> feat : Aws Codebuild 환경 구축 (#209)

buildspec.yml
(#211) buildspec.yml 파일 수정
- buildspec.yml 파일 수정
close #211
=> chore : buildspec.yml 파일 수정 (#211)

buildspec.yml
(#213) buildspec.yml 파일 수정
close #213
=> bug : buildspec.yml 파일 수정 (#213)

buildspec.yml
(#215) buildspec.yml 파일 수정 3
close #215
=> bug : buildspec.yml 파일 수정 3 (#215)

src/main/resources/application-prod.yml
(#217) application-prod.yml 파일 수정
close #217
=> chore : application-prod.yml 파일 수정 (#217)

build.gradle, buildspec.yml, src/main/java/com/plana/infli/infra/config/AWSConfig.java, src/main/java/com/plana/infli/infra/initializer/MemberInitializer.java, src/main/java/com/plana/infli/infra/initializer/PostInitializer.java, src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/java/com/plana/infli/service/CommentService.java, src/main/java/com/plana/infli/service/MailService.java, src/main/java/com/plana/infli/utils/S3Uploader.java, src/main/java/com/plana/infli/web/controller/SettingController.java, src/test/java/com/plana/infli/controller/CommentControllerTest.java
=> bug : CORS 문제 해결 (#223)

deploy/Jenkinsfile
- 디스코드 채널로 배포 현황 할 수 있도록 젠킨스파일 변경
close #225
close #2
close #3
close #4
=> (#225) 디스코드 배포 현황 메세지 전송 기능 추가

buildspec.yml, src/main/resources/application-prod.yml
(#227) Aws Codebuild 관련 코드 수정
close #227
=> chore : Aws Codebuild 관련 코드 수정 (#227)

buildspec.yml
(#231) 빌드 요청시 Jar 파일 꺠지는 문제 해결중 1
close #231
=> bug : 빌드 요청시 Jar 파일 꺠지는 문제 해결중 1 (#231)

buildspec.yml
(#233) 빌드 요청시 Jar 파일 꺠지는 문제 해결중 2
close #233
=> bug : 빌드 요청시 Jar 파일 꺠지는 문제 해결중 2 (#233)

buildspec.yml, src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/infra/initializer/MemberInitializer.java, src/main/java/com/plana/infli/infra/initializer/PostInitializer.java
(#235) 빌드 요청시 Jar 파일 꺠지는 문제 해결중 3
close #235
=> bug : 빌드 요청시 Jar 파일 꺠지는 문제 해결중 3 (#235)

buildspec.yml
(#237) 빌드 요청시 Jar 파일 꺠지는 문제 해결중 4 
close #237
=> bug : 빌드 요청시 Jar 파일 꺠지는 문제 해결중 4 (#237)

buildspec.yml
(#239) 빌드 요청시 Jar 파일 꺠지는 문제 해결중 5
close #239
=> bug : 빌드 요청시 Jar 파일 꺠지는 문제 해결중 5 (#239)

src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java
(#241) Health Check 용 엔드 포인트 설정
- Health Check 용 엔드 포인트 permit all 로 변경 
close #241
=> chore  : Health Check 용 엔드 포인트 설정 (#241)

Dockerfile, build.gradle, buildspec.yml, src/main/resources/application-prod.yml
(#243) AWS ECS 배포환경 설정
close #243
=> chore  : AWS ECS 배포환경 설정 (#243)

buildspec.yml, src/main/java/com/plana/infli/exception/custom/ConflictException.java, src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/java/com/plana/infli/web/controller/AuthController.java, src/main/java/com/plana/infli/web/dto/request/member/signup/company/CreateCompanyMemberRequest.java, src/main/java/com/plana/infli/web/dto/request/member/signup/student/CreateStudentMemberRequest.java, src/test/java/com/plana/infli/controller/AuthControllerTest.java, src/test/java/com/plana/infli/controller/CommentControllerTest.java
(#245) 회원가입 기능 Controller 레이어 테스트 코드 추가
- 학생 회원가입
- 기업 회원가입
- 아이디 중복 확인 
- 닉네임 중복확인 
- 위 해당 기능 Controller 레이어 테스트 코드 작성 
close #245
=> test  : 회원가입 기능 Controller 레이어 테스트 코드 추가 (#245)

src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/java/com/plana/infli/infra/security/entrypoint/CustomAuthenticationEntryPoint.java, src/main/java/com/plana/infli/infra/security/filter/CustomLoginProcessingFilter.java, src/main/java/com/plana/infli/infra/security/handler/CustomAuthenticationFailureHandler.java, src/test/java/com/plana/infli/controller/AuthControllerTest.java
(#247)  EPIC : 로그인, 로그아웃 기능 테스트 코드 작성
- 로그인, 로그아웃 기능 테스트 코드 작성
close #247 
close #248 
close #249
=> (#247) EPIC : 로그인, 로그아웃 기능 테스트 코드 작성

build.gradle, src/main/java/com/plana/infli/domain/Board.java, src/main/java/com/plana/infli/exception/custom/BadRequestException.java, src/main/java/com/plana/infli/exception/custom/ConflictException.java, src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/repository/postlike/PostLikeRepository.java, src/main/java/com/plana/infli/service/PostLikeService.java, src/main/java/com/plana/infli/service/PostService.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/resources/application-test.yml, src/test/java/com/plana/infli/controller/PostLikeControllerTest.java, src/test/java/com/plana/infli/factory/MemberFactory.java, src/test/java/com/plana/infli/factory/PostLikeFactory.java, src/test/java/com/plana/infli/service/PostLikeServiceTest.java, src/test/java/com/plana/infli/service/PostServiceTest.java
(#251) 글 좋아요 관련 기능 테스트 코드 작성
- 글 좋아요, 글 좋아요 취소 기능 테스트 코드 작성 
close #251
=> test  : 글 좋아요 관련 기능 테스트 코드 작성 (#251)

src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/infra/security/config/CustomLoginConfigurer.java, src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/java/com/plana/infli/web/controller/AdminController.java, src/main/java/com/plana/infli/web/controller/AuthController.java, src/main/java/com/plana/infli/web/controller/BoardController.java, src/main/java/com/plana/infli/web/controller/CommentController.java, src/main/java/com/plana/infli/web/controller/CommentLikeController.java, src/main/java/com/plana/infli/web/controller/MemberController.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/controller/PostLikeController.java, src/main/java/com/plana/infli/web/controller/SettingController.java, src/test/java/com/plana/infli/controller/AuthControllerTest.java, src/test/java/com/plana/infli/controller/BoardControllerTest.java, src/test/java/com/plana/infli/controller/CommentControllerTest.java, src/test/java/com/plana/infli/controller/CommentLikeControllerTest.java, src/test/java/com/plana/infli/controller/PostLikeControllerTest.java, src/test/java/com/plana/infli/controller/SettingControllerTest.java
기존 모든 엔드포인트에서  /api 로 시작했던 부분 삭제
(#255) API 엔드포인트 변경
기존 모든 엔드포인트에서  /api 로 시작했던 부분 삭제
close #255
=> chore  : API 엔드포인트 변경 (#255)

src/main/java/com/plana/infli/exception/advice/ExceptionAdvice.java, src/main/java/com/plana/infli/exception/custom/BadRequestException.java, src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryCustom.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryImpl.java, src/main/java/com/plana/infli/service/MemberService.java, src/main/java/com/plana/infli/service/SettingService.java, src/main/java/com/plana/infli/utils/S3Uploader.java, src/main/java/com/plana/infli/web/controller/AuthController.java, src/main/java/com/plana/infli/web/controller/SettingController.java, src/main/java/com/plana/infli/web/dto/request/member/signup/company/CreateCompanyMemberRequest.java, src/main/java/com/plana/infli/web/dto/request/member/signup/student/CreateStudentMemberRequest.java, src/main/java/com/plana/infli/web/dto/request/setting/modify/password/ModifyPasswordRequest.java, src/test/java/com/plana/infli/controller/AuthControllerTest.java, src/test/java/com/plana/infli/controller/BoardControllerTest.java, src/test/java/com/plana/infli/controller/CommentControllerTest.java, src/test/java/com/plana/infli/controller/CommentLikeControllerTest.java, src/test/java/com/plana/infli/controller/PostLikeControllerTest.java, src/test/java/com/plana/infli/controller/SettingControllerTest.java, src/test/java/com/plana/infli/service/BoardServiceTest.java, src/test/java/com/plana/infli/service/CommentLikeServiceTest.java, src/test/java/com/plana/infli/service/MemberServiceTest.java, src/test/java/com/plana/infli/service/PostLikeServiceTest.java, src/test/java/com/plana/infli/service/PostServiceTest.java, src/test/java/com/plana/infli/service/SettingServiceTest.java, src/test/java/com/plana/infli/service/mock/SettingServiceMockTest.java
(#257) 환경 설정 기능 Service 레이어 테스트 코드 작성
- 환경 설정 기능 Service 레이어 테스트 코드 작성 완료
close #257
=> test : 환경 설정 기능 Service 레이어 테스트 코드 작성 (#257)

src/main/java/com/plana/infli/infra/exception/advice/ExceptionAdvice.java, src/main/java/com/plana/infli/repository/post/PostRepositoryCustom.java, src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/dto/request/post/edit/recruitment/EditRecruitmentPostRequest.java, src/test/java/com/plana/infli/annotation/MockMemberFactory.java, src/test/java/com/plana/infli/controller/PostControllerTest.java, src/test/java/com/plana/infli/controller/SettingControllerTest.java, src/test/java/com/plana/infli/mock/SettingServiceMockTest.java
(#261) 글 관련 기능 Controller 레이어 테스트 코드 추가
close #261
=> test  : 글 관련 기능 Controller 레이어 테스트 코드 추가 (#261)

src/main/java/com/plana/infli/infra/exception/custom/NotFoundException.java, src/main/java/com/plana/infli/service/CommentService.java, src/main/java/com/plana/infli/service/MailService.java, src/main/java/com/plana/infli/service/MemberService.java, src/main/java/com/plana/infli/web/controller/AuthController.java, src/test/java/com/plana/infli/controller/PostControllerTest.java, src/test/java/com/plana/infli/factory/MemberFactory.java, src/test/java/com/plana/infli/service/MemberServiceTest.java, src/test/java/com/plana/infli/service/mock/MailServiceMockTest.java, src/test/java/com/plana/infli/service/mock/SettingServiceMockTest.java
(#263)  대학교 인증 메일 링크 엔드포인트 URL 변경
close #263
=> chore  : 대학교 인증 메일 링크 엔드포인트 URL 변경 (#263)

src/main/resources/application-prod.yml
(#265)  Set Cookie 관련 설정 작업
close #265
=> chore : Set Cookie 관련 설정 작업 (#265)

buildspec.yml, src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryCustom.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryImpl.java, src/main/java/com/plana/infli/service/MemberService.java, src/main/java/com/plana/infli/web/controller/AdminController.java, src/main/java/com/plana/infli/web/dto/response/member/verification/company/LoadCompanyVerificationsResponse.java, src/main/java/com/plana/infli/web/dto/response/member/verification/student/LoadStudentVerificationsResponse.java
(#269) 관리자 페이지를 관리자가 접근할수 없는 권한 문제 해결
- 관리자 회원으로 로그인 후 관리자 페이지 접근시 403 에러 발생하는 문제 해결 
close #269
=> bug : 관리자 페이지를 관리자가 접근할수 없는 권한 문제 해결 (269)

src/main/java/com/plana/infli/infra/config/AWSConfig.java, src/main/java/com/plana/infli/infra/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/plana/infli/infra/security/handler/CustomLogoutSuccessHandler.java, src/main/java/com/plana/infli/infra/security/provider/CustomAuthenticationProvider.java, src/main/java/com/plana/infli/infra/security/service/CustomUser.java
(#271) 로그인 성공시 해당 회원의 닉네임, Role 값을 반환하도록 변경
close #271
=> chore : 로그인 성공시 해당 회원의 닉네임, Role 값을 반환하도록 변경 (271)

src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/web/controller/PostController.java
(#273) 키워드로 글 검색시 500 에러 발생하는 문제 해결
close #273
=> bug : 키워드로 글 검색시 500 에러 발생하는 문제 해결 (274)

src/main/java/com/plana/infli/infra/exception/custom/BadRequestException.java, src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/service/PostService.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardServiceRequest.java, src/test/java/com/plana/infli/controller/PostControllerTest.java
(#275) 특정 글에 사진을 다중 첨부하여 업로드 요청시 500 에러 발생하는 문제 해결
close #275
=> bug : 특정 글에 사진을 다중 첨부하여 업로드 요청시 500 에러 발생하는 문제 해결 (275)

src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryCustom.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryImpl.java, src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/service/PostService.java, src/main/java/com/plana/infli/web/controller/PostController.java, src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardServiceRequest.java
(#277) 특정 게시판의 글 목록 조회 기능 Permit All로 변경
- 특정 게시판의 글 목록 조회 기능 로그인 하지 않더라도 조회 가능하도록 변경 
close #277
=> chore : 특정 게시판의 글 목록 조회 기능 Permit All로 변경 (277)

.gitignore, src/main/java/com/plana/infli/repository/comment/CommentRepositoryImpl.java, src/main/resources/application-test.yml
(#285) 특정 글에 작성된 댓글 목록 조회시 500 에러 발생하는 문제 해결
close #285
=> bug : 특정 글에 작성된 댓글 목록 조회시 500 에러 발생하는 문제 해결 (285)

src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/infra/initializer/PostInitializer.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryCustom.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryImpl.java, src/main/java/com/plana/infli/service/CommentService.java, src/main/java/com/plana/infli/service/PostService.java, src/main/resources/application-prod.yml
(#287) 학생 회원이 이메일 인증을 받지 않더라고 글, 댓글 작성 허용하도록 변경
- 학생 회원이 이메일 인증을 받지 않더라고 글, 댓글 작성 허용하도록 변경
close #287
=> chore: 학생 회원이 이메일 인증을 받지 않더라고 글, 댓글 작성 허용하도록 변경 (287)

src/main/resources/application-prod.yml, src/test/java/com/plana/infli/service/CommentServiceTest.java
(#289) 빌드 실패하는 문제 해결
close #289
=> bug : 빌드 실패하는 문제 해결 (289)

src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java, src/main/java/com/plana/infli/web/dto/response/post/search/SearchedPostsResponse.java, src/test/java/com/plana/infli/service/CommentLikeServiceTest.java, src/test/java/com/plana/infli/service/CommentServiceTest.java, src/test/java/com/plana/infli/service/PostServiceTest.java, src/test/java/com/plana/infli/service/mock/PostServiceMockTest.java
(#299) 글 관련 기능 Service 레이어 테스트 코드 추가
- 글 조회 기능 Service 레이어 테스트 코드 추가 
close #299
=> test : 글 관련 기능 Service 레이어 테스트 코드 추가 (299)

src/main/java/com/plana/infli/service/MemberService.java, src/main/java/com/plana/infli/service/PostService.java, src/main/java/com/plana/infli/web/controller/MemberController.java
(#301) 인증 관련 API 코드 개선
- 인증을 받지 않은 회원은 글 , 댓글 작성 하지 못하도록 변경 
- 특정 회원의 인증 상태를 조회하는 API 추가 
close #301 
close #302 
close #303
=> 인증 관련 API 코드 개선

src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java
(#307) CORS 문제 해결
- CORS Allowed Origin https://plan-a-client-7kn9.vercel.app 추가 
close #307
=> bug  : CORS 문제 해결 (307)

src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java
=> bug  : CORS 문제 해결 (311)

src/main/java/com/plana/infli/service/MemberService.java, src/main/java/com/plana/infli/service/util/S3Uploader.java
(#319) CloudFront 사용하도록 코드 변경
- AWS CloudFront를 사용하도록 코드 변경 
close #319
=> feat  : CloudFront 사용하도록 코드 변경 (319)

src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java
(#323) 스웨거 접속이 안되는 문제 해결
close #323
=> bug  : 스웨거 접속이 안되는 문제 해결 (323)

src/main/java/com/plana/infli/infra/initializer/MemberInitializer.java
(#325) 회원 더미 데이터 생성
close #325
=> chore  : 회원 더미 데이터 생성 (325)

buildspec.yml
(#329) buildspec.yml 파일 수정
close #329
=> chore : buildspec.yml 파일 수정 (329)

src/main/java/com/plana/infli/repository/comment/CommentRepositoryImpl.java, src/main/java/com/plana/infli/web/dto/response/comment/view/mycomment/MyComment.java
(#331) https://github.com/Plan-A-project/infli-server/issues/331
- 내가 작성한 댓글 목록 조회시, 댓글이 작성된 게시판의 ID값 반환하도록 추가
close #331 
close #332
=> feat : 내가 작성한 댓글 목록 조회시, 댓글이 작성된 게시판의 ID값 반환하도록 추가 (332)

src/main/java/com/plana/infli/service/MemberService.java
[제목]  // 삭제하고 작성
(#340) 등록이 허용되는 대학교 이메일 형식 추가
- @m.fudan.edu.cn 으로 끝나는 대학교 이메일 형식도 등록이 허용되도록 변경 
close #340
=> chore : 등록이 허용되는 대학교 이메일 형식 추가 (340)

src/main/java/com/plana/infli/service/MemberService.java
(#342) 유효한 대학교 이메일 형식을 유효하지 않다고 응답하는 문제 해결
close #342
=> bug : 유효한 대학교 이메일 형식을 유효하지 않다고 응답하는 문제 해결 (342)

src/main/java/com/plana/infli/repository/member/MemberRepositoryCustom.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryImpl.java, src/main/java/com/plana/infli/service/AdminService.java, src/main/java/com/plana/infli/service/MemberService.java, src/main/java/com/plana/infli/web/controller/AdminController.java, src/main/java/com/plana/infli/web/dto/response/admin/member/LoadSignedUpStudentMembersResponse.java, src/main/java/com/plana/infli/web/dto/response/admin/member/SignedUpStudentMember.java
(#345) 가입한 학생 회원 목록을 조회하는 관리자 기능 추가
- 관리자 페이지에서 가입한 학생 회원 목록을 조회하는 기능 추가
=> 가입한 학생 회원 목록을 조회하는 관리자 기능 추가

build.gradle, src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/java/com/plana/infli/infra/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/plana/infli/infra/security/service/CustomUser.java, src/main/java/com/plana/infli/infra/security/token/CustomAuthenticationToken.java, src/main/resources/application-prod.yml
(#348) Spring Session를 사용하여 세션 저장소 기능 구현
- Spring Session과 Spring Data Redis를 사용하여 세선 저장소 기능 구현
close #348
=> feat : Spring Session를 사용하여 세션 저장소 기능 구현 (348)

src/main/resources/application-prod.yml
(#350) Redis 엔드 포인트 변경
- AWS MemoryDb for Redis 엔드 포인트 변경 
close #350
=> chore : Redis 엔드 포인트 변경 (350)

src/main/resources/application-prod.yml
(#352) 제목  // 삭제하고 작성
[내용]  Redis 클러스터 엔드 포인트 변경
close #352
=> chore : Redis 클러스터 엔드 포인트 변경 (352)

src/main/java/com/plana/infli/infra/security/config/SecurityConfig.java, src/main/resources/application-prod.yml
(#354) Spring Session 설정값 수정
- 로그아웃 요청시 삭제해야 되는 쿠키의 이름 변경
- AWS ElastiCache 엔드 포인트 변경
close #354
=> chore : Spring Session 설정값 수정 (354)

src/main/resources/application-prod.yml
(#356) 제목  // 삭제하고 작성
- session 저장소 엔드 포인트 변수화
close #356
=> chore : session 저장소 엔드 포인트 변수화 (356)

src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java
(#359) 관리자 계정 더미 데이터 추가
close #359
=> chore : 관리자 계정 더미 데이터 추가 (359)

src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryCustom.java, src/main/java/com/plana/infli/repository/member/MemberRepositoryImpl.java, src/main/java/com/plana/infli/service/AdminService.java, src/main/java/com/plana/infli/web/controller/AdminController.java
(#373) 가입한 회원 목록 조회 기능 개선
[내용]  // 삭제하고 작성
- 가입한 회원 목록 조회하는 관리자 기능 개선 
- 가입 회원 목록 조회시 특정 날짜에 가입한 회원만 조회 할수 있는 기능 추가
close #373
=> chore : 가입한 회원 목록 조회 기능 개선 (373)

src/test/java/com/plana/infli/controller/AdminControllerTest.java
(#376) 관리자 기능 Controller 레이어 테스트 코드 추가
close #376
=> test : 가입한 회원 목록 조회 테스트 코드 작성 (376)

src/main/java/com/plana/infli/repository/post/PostRepositoryImpl.java
(#381) 인기글 선정 기준 변경
인기글 선정 기준 
1. 조회수 230이상
2. 댓글 다른 계정 5개 이상
3. 좋아요 3개 이상
close #381
=> chore : 인기글 선정 기준 변경 (381)

src/main/java/com/plana/infli/domain/Board.java
(#384) 게시판 엔티티 구조 변경
close #384
=> chore : 게시판 엔티티 구조 변경 (384)

src/main/java/com/plana/infli/infra/initializer/DefaultInitializer.java
=> bug : 컴파일 오류 해결 (386)
